version: '3.0'

services:
  airflow-init:
    image: ${DOCKER_IMAGE}

    command: >
      bash -c "
      echo '=== Airflow DB init ===' &&
      airflow db init &&
      echo '=== Create admin user ===' &&
      airflow users create
        --username admin
        --firstname lu
        --lastname winston
        --role Admin
        --password admin
        --email winston07291@gmail.com
      "

    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.labels.airflow == true]

    networks:
      - etf_lib_network

networks:
  etf_lib_network:
    external: true
